import {createRequire} from 'node:module';
import {randomBytes,randomUUID} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
import sharp from 'sharp';
const {chromium}=createRequire(import.meta.url)(process.env.STUDIO_PLAYWRIGHT_PATH||'playwright');
const modalities=[['fitness','Modalidade Fitness'],['wellness','Serviço Wellness'],['dance','Modalidade Dance'],['fitness','Pilates'],['fitness','Small Group Training']].map(([area,name])=>({id:randomUUID(),name,area,kind:'group',mode:area==='wellness'?'appointment':name==='Small Group Training'?'information':'schedule',description:'',published:true}));
const member={id:randomUUID(),name:'Pessoa de teste',role:'',bio:'',areas:['fitness','dance'],published:true};
const sessions=[modalities[0],modalities[2],modalities[3]].map(m=>({id:randomUUID(),modalityId:m.id,professionalId:member.id,room:'',recurrence:'weekly',weekday:1,date:'',startDate:'',endDate:'',time:'18:00',duration:50,cancelledDates:[],published:true}));
const original={modalities,professionals:[member],sessions,contact:{email:'',phone:'',address:''}};
const directory=mkdtempSync(join(tmpdir(),'studio601-media-'));process.env.STUDIO_DB_PATH=join(directory,'test.sqlite');
const {database,writeStoredCatalog}=await import('../lib/local-db.mjs');
const {setAdministrator}=await import('../lib/local-auth.mjs');
const password=randomBytes(24).toString('base64url');await setAdministrator('teste-fotos',password);writeStoredCatalog(0,JSON.stringify(original));
const origin='http://127.0.0.1:30608';let server,browser,output='';
async function start(){server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','30608'],{env:{...process.env,APP_ORIGIN:origin},stdio:['ignore','pipe','pipe']});server.stdout.on('data',c=>output+=c);server.stderr.on('data',c=>output+=c);for(let i=0;i<120;i++){if(server.exitCode!==null)throw Error(output);try{if((await fetch(origin+'/api/catalog')).ok)return;}catch{}await delay(250);}throw Error(output);}
async function stop(){if(server&&server.exitCode===null){const stopped=new Promise(r=>server.once('exit',r));server.kill();await stopped;}}
try{
 await start();browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const file={name:'fotografia.png',mimeType:'image/png',buffer:await sharp({create:{width:800,height:600,channels:4,background:{r:80,g:130,b:100,alpha:0.5}}}).png().toBuffer()};
 await page.goto(origin+'/admin');await page.getByLabel('Utilizador',{exact:true}).fill('teste-fotos');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar',exact:true}).click();
 const nav=page.getByRole('navigation',{name:'Gestão do Studio'});await nav.waitFor();
 const upload=async label=>{const ready=page.waitForResponse(r=>r.url()===origin+'/api/media'&&r.request().method()==='POST');await page.getByLabel(label,{exact:true}).setInputFiles(file);assert.equal((await ready).status(),201);await page.getByRole('status').filter({hasText:'A carregar fotografia'}).waitFor({state:'hidden'});};
 const uploadId=async id=>{const ready=page.waitForResponse(r=>r.url()===origin+'/api/media'&&r.request().method()==='POST');await page.locator('#'+id).setInputFiles(file);assert.equal((await ready).status(),201);await page.waitForFunction(()=>!Array.from(document.querySelectorAll('[role=status]')).some(x=>x.textContent.includes('A carregar fotografia')));};
 await nav.getByRole('button',{name:'EQUIPA',exact:true}).click();
 await page.locator('.divide-y>div').filter({has:page.getByText(member.name,{exact:true})}).getByRole('button',{name:'Editar',exact:true}).click();
 await upload('Fotografia do membro da equipa');const firstPortrait=await page.getByRole('dialog').locator('img').getAttribute('src');
 await upload('Fotografia do membro da equipa');assert.notEqual(await page.getByRole('dialog').locator('img').getAttribute('src'),firstPortrait);
 await page.getByRole('dialog').getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 const chosen={};
 for(const area of ['fitness','wellness','dance']){
  await nav.getByRole('button',{name:area.toUpperCase(),exact:true}).click();
  const m=original.modalities.find(m=>m.area===area&&m.published);chosen[area]=m.id;
  await page.locator('.divide-y>div').filter({has:page.getByText(m.name,{exact:true})}).getByRole('button',{name:'Editar',exact:true}).click();
  await page.getByLabel('Descrição',{exact:true}).fill('Texto editado no admin.\nSegunda linha.');await upload('Fotografia da modalidade');
  await page.getByRole('dialog').getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});
 }
 await page.getByRole('tab',{name:'Fotografias',exact:true}).click();
 for(const area of ['fitness','wellness','dance']){await nav.getByRole('button',{name:area.toUpperCase(),exact:true}).click();assert.equal(await page.getByLabel('Fotografia do espaço',{exact:true}).count(),1);assert.equal(await page.locator('input[type=file]').count(),2+original.modalities.filter(m=>m.area===area).length);await uploadId(area+'-card');await uploadId(area+'-space');const target=original.modalities.find(m=>m.id===chosen[area]);const field=page.locator('#modality-photo-'+target.id);const previous=await field.locator('..').locator('img').getAttribute('src');await upload('Fotografia de '+target.name);assert.notEqual(await field.locator('..').locator('img').getAttribute('src'),previous);}
 const stored=page.waitForResponse(r=>r.url()===origin+'/api/catalog'&&r.request().method()==='PUT');await page.getByRole('button',{name:'Guardar fotografias',exact:true}).click();assert.equal((await stored).status(),200);
 let saved=(await(await page.request.get(origin+'/api/catalog?admin=1')).json()).data;
 assert.equal(new Set(['fitness','wellness','dance'].map(a=>saved.sitePhotos[a].spaceImage)).size,3);assert.equal(saved.sitePhotos.spaceImage,undefined);assert.deepEqual(saved.sessions,original.sessions);assert(saved.professionals[0].image);assert.deepEqual(saved.professionals.map(({image,...person})=>person),original.professionals);assert.deepEqual(saved.contact,original.contact);
 for(const m of saved.modalities){const old=original.modalities.find(x=>x.id===m.id);if(Object.values(chosen).includes(m.id)){const {image,description,...rest}=m;const {description:_,...prior}=old;assert.deepEqual(rest,prior);}else assert.deepEqual(m,old);}
 await page.screenshot({path:'outputs/photos-admin-desktop.png',fullPage:true});await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>getComputedStyle(document.querySelector('nav[aria-label="Gestão do Studio"] button')).fontSize==='11px');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.deepEqual(await page.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:innerWidth,overflow:Array.from(document.querySelectorAll('body *')).filter(x=>x.getBoundingClientRect().right>innerWidth+1).map(x=>({tag:x.tagName,class:x.className,slot:x.getAttribute('data-sonner-toaster'),rect:x.getBoundingClientRect().toJSON()}))})),{width:390,viewport:390,overflow:[]});await page.screenshot({path:'outputs/photos-admin-mobile.png',fullPage:true});assert.deepEqual(await page.evaluate(()=>Array.from(document.querySelectorAll('main *')).filter(x=>x.getBoundingClientRect().right>innerWidth+1).map(x=>({tag:x.tagName,class:x.className,width:x.getBoundingClientRect().width}))),[]);
 const media=saved.modalities.find(m=>m.id===chosen.fitness).image;
 let response=await fetch(origin+media);assert.equal(response.status,200);assert.equal(response.headers.get('x-content-type-options'),'nosniff');assert.equal(response.headers.get('content-type'),'image/webp');const bytes=Buffer.from(await response.arrayBuffer());assert.equal((await sharp(bytes).metadata()).format,'webp');assert.equal((await sharp(bytes).metadata()).hasAlpha,true);
 const cookie=(await page.context().cookies()).map(c=>c.name+'='+c.value).join('; ');
 const send=(body,type='image/png',originHeader=origin,auth=cookie)=>fetch(origin+'/api/media',{method:'POST',headers:{'Content-Type':type,Origin:originHeader,...(auth?{Cookie:auth}:{})},body});
 assert.equal((await send(file.buffer,'image/png',origin,'')).status,403);assert.equal((await send(file.buffer,'image/png','https://untrusted.example')).status,403);assert.equal((await send('<svg onload="alert(1)"></svg>')).status,400);assert.equal((await send('<svg/>','image/svg+xml')).status,415);assert.equal((await send(Buffer.alloc(10*1024*1024+1))).status,413);assert.equal((await send(file.buffer.subarray(0,20))).status,400);assert.equal((await send(await sharp(file.buffer).jpeg().toBuffer(),'image/jpeg')).status,201);assert.equal((await send(bytes,'image/webp')).status,201);assert.equal((await fetch(origin+'/api/media/not-a-photo.webp')).status,404);
 const invalid=structuredClone(saved);invalid.modalities[0].image='javascript:alert(1)';const version=(await(await page.request.get(origin+'/api/catalog?admin=1')).json()).version;assert.equal((await page.request.put(origin+'/api/catalog',{headers:{Origin:origin},data:{version,data:invalid}})).status(),400);
 const invalidSpace=structuredClone(saved);invalidSpace.sitePhotos.fitness.spaceImage='https://untrusted.example/photo.png';assert.equal((await page.request.put(origin+'/api/catalog',{headers:{Origin:origin},data:{version,data:invalidSpace}})).status(),400);
 const invalidPerson=structuredClone(saved);invalidPerson.professionals[0].image='https://untrusted.example/photo.png';assert.equal((await page.request.put(origin+'/api/catalog',{headers:{Origin:origin},data:{version,data:invalidPerson}})).status(),400);
 const loaded=page.waitForResponse(r=>r.url()===origin+'/api/catalog');await page.goto(origin);await loaded;
 for(const width of [1440,390,320]){await page.setViewportSize({width,height:900});for(const area of ['fitness','wellness','dance']){await page.locator('.dock [data-select="'+area+'"]').click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('img.managed-photo')).every(x=>x.complete&&x.naturalWidth>0));const m=saved.modalities.find(m=>m.id===chosen[area]);assert.equal(await page.locator('.studio-visual .managed-photo').getAttribute('src'),saved.sitePhotos[area].spaceImage);const card=page.locator('.series-card').filter({has:page.getByRole('heading',{name:m.name,exact:true})});assert.equal(await card.locator('.managed-photo').getAttribute('src'),m.image);assert.match(await card.innerText(),/Texto editado no admin/);const portrait=page.locator('.team-track .team-portrait').filter({has:page.getByText(member.name,{exact:true})});if(member.areas.includes(area)){assert.equal(await portrait.count(),1);assert.equal(await portrait.locator('.managed-photo').getAttribute('src'),saved.professionals[0].image);assert.equal(await portrait.locator('.asset-label').isVisible(),false);assert.equal(await portrait.locator('.portrait-info strong').isVisible(),true);assert.equal(await portrait.locator('.managed-photo').evaluate(img=>getComputedStyle(img).zIndex),'-2');if(area==='fitness'&&[1440,390].includes(width))await portrait.screenshot({path:'outputs/team-photo-'+width+'.png'});await portrait.click();assert.equal(await page.locator('dialog[open]').count(),0);}else assert.equal(await portrait.count(),0);assert.equal(await page.locator('#horarios').isVisible(),area!=='wellness');await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);if(width===390&&area==='fitness')await card.screenshot({path:'outputs/photos-public-mobile.png'});}
 await page.locator('.dock [data-select="all"]').click();for(const area of ['fitness','wellness','dance'])assert.equal(await page.locator('.area-card[data-go="'+area+'"] .area-photo').getAttribute('src'),saved.sitePhotos[area].cardImage);}
 await stop();await start();assert.deepEqual((await(await page.request.get(origin+'/api/catalog?admin=1')).json()).data,saved);assert.deepEqual(Buffer.from(await(await fetch(origin+media)).arrayBuffer()),bytes);assert.equal((await fetch(origin+saved.professionals[0].image)).status,200);await page.goto(origin+'/admin');await page.getByRole('tab',{name:'Fotografias',exact:true}).click();await page.getByRole('navigation',{name:'Gestão do Studio'}).getByRole('button',{name:'WELLNESS',exact:true}).click();await page.locator('#wellness-space').waitFor();assert.equal(await page.getByLabel('Fotografia do espaço',{exact:true}).count(),1);assert.equal(await page.locator('#wellness-space').locator('..').locator('img').getAttribute('src'),saved.sitePhotos.wellness.spaceImage);
 const space=page.locator('fieldset').filter({has:page.locator('#wellness-space')});await space.getByRole('button',{name:'Remover fotografia',exact:true}).click();const well=page.locator('fieldset').filter({has:page.locator('#wellness-card')});await well.getByRole('button',{name:'Repor fotografia original',exact:true}).click();
 const cleared=page.waitForResponse(r=>r.url()===origin+'/api/catalog'&&r.request().method()==='PUT');await page.getByRole('button',{name:'Guardar fotografias',exact:true}).click();assert.equal((await cleared).status(),200);
 const reloaded=page.waitForResponse(r=>r.url()===origin+'/api/catalog');await page.goto(origin);await reloaded;await page.locator('.dock [data-select="wellness"]').click();await page.waitForFunction(()=>document.querySelector('.area-card[data-go="wellness"] .area-photo').getAttribute('src')==='/photos/wellness.png');assert.equal(await page.locator('.studio-visual .managed-photo').count(),0);for(const area of ['fitness','dance']){await page.locator('.dock [data-select="'+area+'"]').click();assert.equal(await page.locator('.studio-visual .managed-photo').getAttribute('src'),saved.sitePhotos[area].spaceImage)}assert.equal((await fetch(origin+media)).status,200);assert.deepEqual(errors,[]);
 await page.goto(origin+'/admin');const teamNav=page.getByRole('navigation',{name:'Gestão do Studio'});await teamNav.waitFor();await teamNav.getByRole('button',{name:'EQUIPA',exact:true}).click();await page.locator('.divide-y>div').filter({has:page.getByText(member.name,{exact:true})}).getByRole('button',{name:'Editar',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Remover fotografia',exact:true}).click();await page.getByRole('dialog').getByRole('button',{name:'Guardar',exact:true}).click();await page.getByRole('dialog').waitFor({state:'hidden'});assert.equal((await(await page.request.get(origin+'/api/catalog?admin=1')).json()).data.professionals[0].image,'');const teamLoaded=page.waitForResponse(r=>r.url()===origin+'/api/catalog');await page.goto(origin);await teamLoaded;assert.equal(await page.locator('.team-track .managed-photo').count(),0);assert.equal(await page.locator('.team-track .asset-label').isVisible(),true);
 console.log(JSON.stringify({result:'PASS',teamPhoto:'upload, replacement, multi-area display, removal and restart PASS',modalitiesEdited:3,areaCards:3,areaSpaces:3,security:'PASS',restartPersistence:'PASS',realDatabaseWrites:0,viewports:[1440,390,320]}));
}finally{await browser?.close();await stop();database().close();const target=resolve(directory);assert(target.startsWith(resolve(tmpdir())+sep)&&target!==resolve(tmpdir()));rmSync(target,{recursive:true,force:true});}
