import {createRequire} from 'node:module';
import {randomBytes} from 'node:crypto';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join,resolve,sep} from 'node:path';
import {spawn} from 'node:child_process';
import assert from 'node:assert/strict';
import {setTimeout as delay} from 'node:timers/promises';
import {empty} from '../lib/catalog.ts';
import {importFitness} from '../lib/fitness-import.mjs';
import {importDance} from '../lib/dance-import.mjs';
import {importWellness} from '../lib/wellness-import.mjs';
const {chromium}=createRequire(import.meta.url)(process.env.STUDIO_PLAYWRIGHT_PATH||'playwright');
const directory=mkdtempSync(join(tmpdir(),'studio601-schedule-'));
process.env.STUDIO_DB_PATH=join(directory,'test.sqlite');
const {database,writeStoredCatalog}=await import('../lib/local-db.mjs');
const {setAdministrator}=await import('../lib/local-auth.mjs');
const password=randomBytes(24).toString('base64url');await setAdministrator('teste-horarios',password);
const original=importWellness(importDance(importFitness(empty).data).data).data;
writeStoredCatalog(0,JSON.stringify(original));
const pump=original.modalities.find(m=>m.name==='Pump'),initial=original.sessions.filter(s=>s.modalityId===pump.id);
const origin='http://127.0.0.1:30607';let server,browser,output='';
async function start(){server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','--hostname','127.0.0.1','--port','30607'],{env:{...process.env,APP_ORIGIN:origin},stdio:['ignore','pipe','pipe']});server.stdout.on('data',c=>output+=c);server.stderr.on('data',c=>output+=c);for(let i=0;i<120;i++){if(server.exitCode!==null)throw Error(output);try{if((await fetch(origin+'/api/catalog')).ok)return;}catch{}await delay(250);}throw Error(output);}
async function stop(){if(server&&server.exitCode===null){const stopped=new Promise(r=>server.once('exit',r));server.kill();await stopped;}}
try{
 await start();browser=await chromium.launch({channel:'msedge',headless:true});
 const page=await browser.newPage({viewport:{width:1440,height:900},reducedMotion:'reduce'}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/admin');await page.getByLabel('Utilizador',{exact:true}).fill('teste-horarios');await page.getByLabel('Password',{exact:true}).fill(password);await page.getByRole('button',{name:'Entrar',exact:true}).click();
 await page.getByRole('tab',{name:'Turmas e sessões',exact:true}).click();
 const group=page.locator(`[data-schedule-modality="${pump.id}"]`),dialog=page.getByRole('dialog');
 await group.waitFor();assert.equal(await page.getByRole('heading',{name:'Pump',exact:true}).count(),1);assert.equal(await group.locator('[data-schedule-session]').count(),4);
 assert.equal(await page.getByRole('heading',{name:'Pump | Attack',exact:true}).count(),1);
 await page.getByRole('tab',{name:'Modalidades e serviços',exact:true}).click();
 await page.locator('.divide-y>div').filter({has:page.getByText('Pump',{exact:true})}).getByRole('button',{name:'Horários',exact:true}).click();
 assert.equal(await page.locator('[data-schedule-modality]').count(),1);
 await group.getByRole('button',{name:'Adicionar horário',exact:true}).click();
 assert.equal(await dialog.getByRole('combobox').first().textContent(),'Pump');
 await dialog.getByRole('combobox').nth(3).click();await page.getByRole('option',{name:'Quarta',exact:true}).click();
 await dialog.getByLabel('Hora de início',{exact:true}).fill('10:00');await dialog.getByLabel('Duração (minutos)',{exact:true}).fill('50');
 await dialog.getByLabel('Datas sem aula',{exact:false}).fill('2026-09-23');await dialog.getByRole('switch',{name:'Publicado no site',exact:true}).check();
 await dialog.getByRole('button',{name:'Guardar',exact:true}).click();await dialog.waitFor({state:'hidden'});
 assert.equal(await group.locator('[data-schedule-session]').count(),5);
 const saved=(await(await page.request.get(origin+'/api/catalog?admin=1')).json()).data;
 assert.deepEqual(saved.modalities,original.modalities);assert.deepEqual(saved.professionals,original.professionals);
 const added=saved.sessions.find(s=>!original.sessions.some(old=>old.id===s.id));assert.equal(added.modalityId,pump.id);assert.deepEqual(added.cancelledDates,['2026-09-23']);assert.equal(added.published,true);
 for(const old of original.sessions)assert.deepEqual(saved.sessions.find(s=>s.id===old.id),old);
 await group.screenshot({path:'outputs/pump-admin-desktop.png'});
 const target=initial.find(s=>s.weekday===2&&s.time==='11:00');
 await group.locator(`[data-schedule-session="${target.id}"]`).getByRole('button',{name:'Editar',exact:true}).click();
 await dialog.getByLabel('Hora de início',{exact:true}).fill('11:05');await dialog.getByRole('button',{name:'Guardar',exact:true}).click();await dialog.waitFor({state:'hidden'});
 await page.setViewportSize({width:390,height:844});await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await group.screenshot({path:'outputs/pump-admin-mobile.png'});
 await page.goto(origin);await page.locator('[data-select="fitness"]').click();await page.waitForFunction(()=>document.querySelector('#timetable-body').textContent.includes('11:05'));
 assert.equal(await page.locator('.series-title').filter({hasText:/^Pump$/}).count(),1);
 assert.equal(await page.locator('.timetable-event').filter({has:page.locator('strong',{hasText:/^Pump$/})}).count(),5);
 await page.goto(origin+'/admin');await page.getByRole('tab',{name:'Turmas e sessões',exact:true}).click();
 await group.locator(`[data-schedule-session="${added.id}"]`).getByRole('button',{name:'Eliminar',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'Eliminar',exact:true}).click();await page.getByRole('alertdialog').waitFor({state:'hidden'});
 assert.equal(await group.locator('[data-schedule-session]').count(),4);
 const expected=(await(await page.request.get(origin+'/api/catalog?admin=1')).json()).data;
 assert.deepEqual(expected.modalities,original.modalities);assert.deepEqual(expected.professionals,original.professionals);assert.deepEqual(expected.contact,original.contact);
 for(const old of original.sessions)assert.deepEqual(expected.sessions.find(s=>s.id===old.id),old.id===target.id?{...old,time:'11:05'}:old);
 await stop();await start();assert.deepEqual((await(await page.request.get(origin+'/api/catalog?admin=1')).json()).data,expected);
 assert.deepEqual(errors,[]);console.log('Pump: uma modalidade, quatro horários agrupados, adicionar/editar/publicar/cancelar/eliminar um horário, site com um card e várias sessões, mobile e reinício verificados; restantes dados preservados.');
}finally{if(browser)await browser.close();await stop();database().close();assert(resolve(directory).startsWith(resolve(tmpdir())+sep)&&directory.includes('studio601-schedule-'));rmSync(directory,{recursive:true,force:true});}
